### ISSUE TITLE
Try to read .bowerrc

### ISSUE THREAD

**Issue by xxorax** [ksmithut/bower-files#34]
For automaticaly retrieve the bower folder where the components are installed, it should read the .bowerrc file. There is an option inside to define the folder :
```
{
	"directory": "public/lib"
}
```

Thanks !

**Comment by ksmithut** [comment]
@xxorax sounds easy enough. I'll start work right away.

**Comment by ksmithut** [comment]
@xxorax Looks like respecting the rules of .bowerrc will take some time, but I also think it's important.

This is how I'm thinking the configuration will take precedence.
1. Top priority is what is passed in through the JS API (`require('bower-files')({...});`)
1. Next is `bower.json`. This is used by the JS API
1. Next is the local `.bowerrc`. This can pass in the `cwd` and `directory` options
1. Next are all of the `.bowerrc` files upwards in the directory tree
1. Next is the `.bowerrc` in the Home directory (`~`)
1. Next is the `.bowerrc` in the global directory (`/`)

I think I might need to work on a 3.x branch for this and #35. They're features I'd like to implement, it will just take a lot of refactoring to keep the codebase clean.

**Comment by ksmithut** [comment]
@xxorax Just giving you an update, I'm working on a refactor. I won't be done as quickly as I thought, but I hope to be able to finish it sometime tomorrow. If it doesn't break anything, I'll keep it in the 2.x branch. Perhaps, I'll just keep it there and deprecate some options.

**Comment by xxorax** [comment]
Yes, I didn't have reflexion about this but it's finaly more difficult than it appear.
Maybe we should re-use the bower library like [bower/config](https://github.com/bower/config).
Thanks !

**Comment by ksmithut** [comment]
[https://github.com/bower/config](bower/config) is working out nicely :) I've got all the old tests passing, so now I just need to write the new ones for this.

**Comment by ksmithut** [comment]
@xxorax I've got a beta version out on npm

```bash
npm install bower-files@3.0.0-beta.0
```

It's got this functionality built in :) Give it a try and let me know what you think. Be sure to read up on the [new docs](https://github.com/ksmithut/bower-files/tree/3.x). If you and other like how things are, I'll merge them into master and publish it as a non-beta version.

**Comment by ksmithut** [comment]
This is resolve now. 3.0.0 was published. Be sure to note the new api in the documentation.
