### ISSUE TITLE
Exclude minified files

### ISSUE THREAD

**Issue by devmondo** [ksmithut/bower-files#36]
awesome plugin, it is working great, but how can i exclude minified files ? like some packages have minified file in the bower json main option.

thanks in advanced.

**Comment by shinnn** [comment]
Probably `options.overrides` helps you.

**Comment by ksmithut** [comment]
Exactly. To be clear, you can specify an override value for the main option for specific packages in your bower.json or in the options you pass in.

bower.json example:

    {
      ...
      "overrides": {
        "jquery": {
          "main": "dist/jquery.js"
        }
      }
    }

Does that make sense?

**Comment by ksmithut** [comment]
I should also note that the path value you pass into the main option is relative to the component directory, so the above example is going to use bower_components/jquery/dist/jquery.js.

**Comment by shinnn** [comment]
The best solution for the problem is creating a pull request for the library to exclude minified files from `main`. Including minified files in `main` doesn't match [bower package guideline](https://github.com/bower/bower.json-spec#main).

**Comment by devmondo** [comment]
thanks all for reply, really helpful

i was thinking of something simpler like gulp.src (['!*min.js'])

**Comment by ksmithut** [comment]
I've recently be working on a 3.x branch and will probably be working in a globbing feature like that. I'll keep this issue open and keep you updated on the progress of that branch.

**Comment by devmondo** [comment]
@ksmithut, thanks a lot for the reply, and for the hints,

sure PR is good, but when you implement globbing, it will allow us for really fancy scenarios

**Comment by ksmithut** [comment]
@shinnn @devmondo There's a discussion going on in #35 about a new API. It requires some breaking changes, but I think it would allow a much more flexible API that feels a lot better to work with. I would love your feedback!

**Comment by ksmithut** [comment]
This is now published in version 3.0.0
