### ISSUE TITLE
Add module name to files array

### ISSUE THREAD

**Issue by swemaniac** [ksmithut/bower-files#40]
This is the most promising gulp/bower files module I've seen so far but it's lacking one tiny thing (for me) which is to provide the name of the dependency in the resulting files array, i.e.: {'jquery': '/bower_components/jquery.js'}

This would enable me to use this in conjunction with Browserify in the following standard manner: browserify.require(file, { expose: id }) (where id is the module name). 

I guess it would be a breaking change though, unless a new method/option is introduced.

**Comment by shinnn** [comment]
Did you try [debowerify](https://github.com/eugeneware/debowerify)?

**Comment by swemaniac** [comment]
That's just for javascript files though, and debrowserify won't solve my problem.. I'm currently using bower-files and bower-resolve to solve one problem each but it would be nice to have only one dependency that solves both :)

**Comment by ksmithut** [comment]
I think we could add in another virtual property to the method chaining to accomplish this. What would you think about something like this:

```javascript
var lib = require('bower-files')();

var deps = lib.self().ext('js').deps;
```

Where `deps` is the hash of all of your bower components with whatever filtering you applied. So you wouldn't need to use the `.self()` or `.ext('js')`, and you could just use `lib.deps` to get the full list of object hashes.

```javascript
var lib = require('bower-files')().deps;

lib.jquery;
lib.bootstrap;
```

That should not break anything the way I've rebuilt it. The only thing is that to be consistent, we'll probably have to return an array of the files included in each dependency. For example, bootstrap has multiple main files to be included (.css, .less, .js, font files). Is that something that you could work around in your current setup?

**Comment by swemaniac** [comment]
Thanks for the reply. Yes for this to be useful we need a connection between deps and files as you mention. It will get a bit redundant though, since the `files` property already contain the paths but something along the lines of this seems logical to me (note that I'm not 100% aware of all the ins and outs of this lib yet):

```javascript
var lib = require('bower-files')().deps;

lib.bootstrap {
   js: ['/var/www/etc/dist/bootstrap.js', 'etc'],
   less: [],
   css: []
}
````

or with filtering of just one ext:

```javascript
var lib = require('bower-files')().ext('js').deps;

lib.bootstrap [
       '/var/www/etc/dist/bootstrap.js',
       'etc'
]
````

What do you think?

**Comment by ksmithut** [comment]
Ooh, yes, I like it. I'll start writing some tests, and hopefully have this out by the end of the day.

**Comment by swemaniac** [comment]
Awesome :)

**Comment by ksmithut** [comment]
So we're saying the the dependencies should be split by extension by default, correct?

By default, `files` returns an array, but with `.ext(true)` we get all of the files, but as an object with all of the extensions as properties.
```javascript
var lib = require('bower-files')();

lib.ext(true).files // { js: [...], css: [...]
```

So you're saying it should be split by extension for each dependency by default, correct? I worry a little bit about the inconsistency between the options used between the two. If we keep the options the same, you would just need to do the following to get the desired result:

```javascript
var lib = require('bower-files')().ext(true).deps;

lib.bootstrap/ // { js: [...], css: [...], less: [...]}
```

I'm fine doing it either way, it's more a matter of convention and avoiding confusion.

**Comment by swemaniac** [comment]
Oh no yeah that's definitely the better way to go, I didn't know about the `ext(true)` option. It makes a lot of sense doing it that way, keeping the options the same.

**Comment by ksmithut** [comment]
Cool, I should have tests and new functionality deployed to npm something this morning. I'll keep you posted.

**Comment by swemaniac** [comment]
Thanks I appreciate it :)

/Johan
--
Utvecklare @ Bazooka
08 31 70 00 | www.bazooka.se

**Comment by ksmithut** [comment]
@swemaniac It's been publish to npm, v3.3.0. Let me know if you have any issues with it!

**Comment by swemaniac** [comment]
Cool that was fast, I'll have to check it out tomorrow morning (GMT+1 :)

/Johan
--
Utvecklare @ Bazooka
08 31 70 00 | www.bazooka.se

**Comment by swemaniac** [comment]
Hi I'm really sorry for not getting back to you sooner but I've tried this recently and works great for getting the deps with their IDs, nice work!

One thing though, as the vendor IDs are stripped of hyphens there's no way to use the IDs directly when exposing them to browserify or what have you (you would still need the original ID, e.g. 'jquery-whatever-plugin'). I realize that to keep the hyphens the keys in the object need to be strings, or included in another way.. ;) I could do it on my side, reverting them, but I think the IDs in the returned object should point to something that exists. Do you have an insight on this?

**Comment by ksmithut** [comment]
That does make sense to keep the original ids in there. What if we were to put a `camelCase` option at the `require('bower-files')(...)` level?

Example:

```js
var lib = require('bower-files')({camelCase: false}).deps;

lib['angular-route']
```

Either that or I could provide both the camelcased version and the hyphenated version and just have the camelcased key point to the hyphenated on. That may cause confusion if someone were to iterate over the keys of the deps object.

Both of those solutions would make it so I don't have to make a breaking change to the API. I should have waited until you took a look at it before I published, and I apologize.

**Comment by swemaniac** [comment]
No worries, I was late replying anyway. I'd say go with the option you prefer :)

**Comment by ksmithut** [comment]
@swemaniac I've added in the `camelCase` option as described above in the latest version. Want to get it a try and let me know if that's what you were looking for?

**Comment by swemaniac** [comment]
@ksmithut I just tried it out on a real-world project and it works great, now I can finally remove the dependency on "bower-resolve" and use "bower-files" for both css and js files. Thanks for this mate!

Basically what I'm able to do now is to automatically include and require js files from bower into browserify, which previously I had to use the other module for exclusively.

```javascript
var browserify = require('browserify');
var bowerDeps = require('bower-files')({ cwd: __dirname + '/' + ASSETS_PATH, camelCase: false }).ext('js')deps();

Object.keys(bowerDeps).forEach(function(id) {
    var mainFile = bowerDeps[id][0];
    browserify.require(mainFile, { expose: id });
}
```

You can close this if you're happy with it :)
