### ISSUE TITLE
woff2 file support

### ISSUE THREAD

**Issue by boogerlad** [ksmithut/bower-files#42]
`bowerSrc.ext(['eot', 'woff', 'woff2', 'ttf', 'svg']).files` seems to be excluding woff2 files. Perhaps there is a bug when there exists a number in the file extension?

**Comment by ksmithut** [comment]
Possibly, which bower component are you trying to include that has a woff2 file in it?

**Comment by boogerlad** [comment]
Twitter Bootstrap.

**Comment by ksmithut** [comment]
Looks like it might be an issue with bower, or the team publishing bootstrap to bower. I see the `woff2` file being [included in their bower.json](https://github.com/twbs/bootstrap/blob/master/bower.json#L24), but when I download it, it shows that the `woff2` file isn't included in the "main" property. I would submit an issue with bootstrap or bower to get that resolved. They may not have published the new bower.json just yet to bower yet.

In the meantime, you can add it manually in your overrides option documented [here](https://github.com/ksmithut/bower-files#optionsoverrides-object).

**Comment by boogerlad** [comment]
Huh, you're right. I manually checked it a couple days ago and it was included in the main repository. Now it isn't. Sorry for bothering you.

**Comment by ksmithut** [comment]
@boogerlad No worries, it wasn't a bother at all. It always helps to get feedback.
