### ISSUE TITLE
Error: Missing positive glob

### ISSUE THREAD

**Issue by darren131** [ksmithut/bower-files#44]
Hi there,

Getting a strange message (Error: Missing positive glob) that I'm hoping you'll be able to help with... Here's my code

```javascript
var gulp = require('gulp'); 
var bowerFiles = require('bower-files')();
var $ = require('gulp-load-plugins')();
var conf = {
    "paths": {
        ...
        "javascript": {
            "src": ["src/scripts/*.js"],
            "dest": "public/js"
        },
        ...
    };

gulp.task('scripts', function() {
    return gulp.src([conf.paths.javascript.src, bowerFiles.ext('js').files])
        .pipe($.concat('main.js'))
        .pipe($.uglify())
        .pipe(gulp.dest(conf.paths.javascript.dest));
});

```

Totally stumped... probably something quite simple...?

Thanks!

**Comment by shinnn** [comment]
```js
gulp.src([conf.paths.javascript.src, bowerFiles.ext('js').files])
```

↓

```js
gulp.src(conf.paths.javascript.src.concat(bowerFiles.ext('js').files))
```

**Comment by ksmithut** [comment]
Thanks @shinnn! So `gulp.src` is expecting an array of glob strings. What you've got is an array of arrays of glob strings. What @shinnn has suggested that you do is flatten the array by concatenating the arrays together so that you get a single array.

**Comment by ksmithut** [comment]
Just to add to that, gulp will return that error if it can't determine a positive glob pattern from the given glob or array of globs. So if you only have negative globs: `['!src/**/*']` or if you have an array of things that aren't globs such as what you have there, then gulp will throw the error `Error: Missing positive glob`.

Does that make sense?

**Comment by ksmithut** [comment]
@darren131 Did you get things figured out? If you need any additional help, feel free to reach out.

I'm going to close it for now, but feel free to open it back up if we didn't resolve your issue.

**Comment by darren131** [comment]
Thanks Keith,

I figured it out.

On 18 February 2015 at 04:08, Keith Smith <notifications@github.com> wrote:

> @darren131 <https://github.com/darren131> Did you get things figured out?
> If you need any additional help, feel free to reach out.
>
> I'm going to close it for now, but feel free to open it back up if we
> didn't resolve your issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ksmithut/bower-files/issues/44#issuecomment-74681955>.
>



-- 
Darren Wood • The Fold
+64 21 78 45 78

**Comment by koganalon** [comment]
ffdggdfdfgfgds
