### ISSUE TITLE
Add CLI?

### ISSUE THREAD

**Issue by pluma** [ksmithut/bower-files#47]
I wrote a CLI wrapper called [bower-ls](https://www.npmjs.com/package/bower-ls). With the new API the implementation is [basically a one-liner](https://github.com/pluma/bower-ls/blob/master/bin/bower-ls).

Would you be interested in adding a CLI or merging mine into the project?

**Comment by ksmithut** [comment]
@pluma I think that's a great idea :smiley: Would you like to submit a pull request? If not, that's fine, I just want to make sure that credit is given where it's due.

**Comment by pluma** [comment]
@ksmithut Sounds good. I'll open a PR then :+1:
