### ISSUE TITLE
Add Ability to get only Dev Dependencies

### ISSUE THREAD

**Issue by fracmak** [ksmithut/bower-files#53]
So I have a need to only list the dev dependencies without the normal dependencies. There's multiple ways to go about implementing this, but I was looking for some guidance on how you'd like it to be done. I could expand the .dev() option to be "add dev" vs "dev exclusive". I could add another option .devOnly()? I could add a .devFiles instead of .files. 

Thoughts?

**Comment by ksmithut** [comment]
Hmmm... I never thought of that. Perhaps having an option for the regular dependencies like `main`, so you could disable the main dependencies with something like `.main(false)`. What do you think?

**Comment by fracmak** [comment]
Ooh, I like that. I'll get cracking on that

**Comment by ksmithut** [comment]
Awesome, thanks :)
