### ISSUE TITLE
font awesome and mdi

### ISSUE THREAD

**Issue by jmls** [ksmithut/bower-files#55]
I'm sorry to have to raise an issue to ask this question, but can't find a group or wiki. I am struggling to get fontawesome and mdi to work with bower-files and gulp

are there any hints or clues to guide me in my quest ?

thanks

**Comment by ksmithut** [comment]
Sure thing :)

What do your `bower.json` and `gulpfile.js` look like? For the `gulpfile.js`, I would only need to know how you're using `bower-files`, but we should be able to get you going pretty quickly once I find those things out.

**Comment by jmls** [comment]
thanks! everything seems ok, and I can use bower-files to generate the js files peachy. However, I don't know what to put into the gulp command for something like fa where it has fonts and woffs and all sorts of other stuff ... ;)

bower.json
```javascript
{
  "name": "myApp",
  "main": "index.js",
  "version": "0.0.1",
  "ignore": [
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "d3": "~3.5.5",
    "lumx": "~0.3.31",
    "angular-animate": "~1.3.15",
    "angular-aria": "~1.3.15",
    "angular-cookies": "~1.3.15",
    "angular-drag-and-drop-lists": "~1.2.0",
    "angular-messages": "~1.3.15",
    "angular-resource": "~1.3.15",
    "angular-tooltips": "~0.1.9",
    "angular-ui": "~0.4.0",
    "angular-ui-router": "~0.2.14",
    "ng-websocket": "~0.2.1",
    "velocity": "*",
    "moment": "~2.10.2",
    "angular": "~1.3.15"
  }
}
```
gulp task for js development : 
```javascript
gulp.task('development', function() {
  gulp.src(bowerFiles.ext('js').files)
    .pipe(concat('vendor.js'))
    .pipe(gulp.dest('lib/client/dist/js'))
});
```
css 
```javascript
gulp.task('developmentCSS', function() {
  gulp.src(bowerFiles.ext('css').files)
    .pipe(concat('vendor.css'))
    .pipe(gulp.dest('lib/client/dist/css'))
});
```

obviously this doesn't work for fa or mdi and I was wondering what I needed to add where ;)

many thanks

**Comment by ksmithut** [comment]
Are the bower package `font-awesome` and `mdi` dependencies of one of your bower dependencies? If not, run `bower install --save font-awesome mdi` to install `font-awesome` and `mdi` first.

The other thing that I notices is that the `mdi` package has their `"main"` files all messed up, so you'll need to add the following to your `bower.json` to make sure you don't get all of the junk they included:

```json
{
  ...
  "overrides": {
    "mdi": {
      "main": [
        "fonts/*",
        "css/materialdesignicons.min.css"
      ]
    }
  }
}
```

Next, you'll want to add a new task to copy the font files to where you need them.

```js
gulp.task('fonts', function () {
  gulp.src(bowerFiles.ext(['eot', 'svg', 'ttf', 'woff', 'woff2', 'otf']).files)
    .pipe(gulp.dest('lib/client/dist/fonts'));
});
```

The css files from those bower components should already be included in your build process :)

Let me know if that works for you and what other issues you run into.

**Comment by jmls** [comment]
that seems to have done the trick ! many thanks !

**Comment by ksmithut** [comment]
You bet :smile: Glad I could help. Feel free to reopen the issue if you run into more issues.
