### ISSUE TITLE
specify order of js files

### ISSUE THREAD

**Issue by jmls** [ksmithut/bower-files#56]
I have a need to ensure that jquery is loaded before angular. Is this possible with bower-files ?

**Comment by ksmithut** [comment]
Yes, you can override the dependencies for a package in your `bower.json` overrides:

`bower.json`
```json
{
  ...
  "overrides": {
    "mdi": {
      "main": [
        "fonts/*",
        "css/materialdesignicons.min.css"
      ]
    },
    "angular": {
      "dependencies": {
        "jquery": "*"
      }
    }
  }
}
```

**Comment by jmls** [comment]
worked well. thanks again. Is it ok to create issues like this for questions ? - at the very least they can be searched by other people with the same problem

**Comment by ksmithut** [comment]
Yes, this is the place to do it. It's difficult to cover every use case in the documentation, which is already pretty big. I think I've run into this specific issue enough time to put it into the documentation.

So yes, feel free to open issues for any question that you might have :) This is useful for other people like you mentioned, and it also starts up larger discussion for functionality that isn't included yet.
