### ISSUE TITLE
`self` option doesn't work

### ISSUE THREAD

**Issue by jfbibeau** [ksmithut/bower-files#57]
I'm finding that the 'self' option is not quite working, unless I'm doing something wrong?

For example, my bower.json has a few files listed under main, but the following code returns all the dependencies, without my main files:
```
var extlib = require('bower-files')({camelCase: false});

gulp.task('test', function() {
   console.log(extlib.self().files);
});
```

Running `gulp test` returns me a list of files, but my own main[] files are not included. I would expect to see file1 and file2 in the list of files returned as they are in my bower.json:

```
"main": [
        "js/file1",
        "js/file2",
...
  ],
```

**Comment by jfbibeau** [comment]
Gah, never mind, found out why. My files declared in bower.json have the wrong path (they are the path from when I build the package, not the current path). Closing :)

**Comment by ksmithut** [comment]
No worries :) let me know if you have any other questions
