### ISSUE TITLE
Order of .files vs .deps

### ISSUE THREAD

**Issue by jfbibeau** [ksmithut/bower-files#58]
Hi! Me again.

I noticed that if I call .files, I will get the list of files returned in the correct order (proper loading order for the browser).

However, if I call .deps, the order is different. 

I'm trying to get a list of dependencies, concat each one, minify it, then inject it in my html page.

However it doesn't seem I can rely on .deps as the order returned is different than .files. Is that design intent?

**Comment by ksmithut** [comment]
`.deps` is an object hash, and `.files` is an array. `.deps` is used if you want to access the files for a specific bower component (i.e. `.deps.jquery` or `.deps.bootstrap`). Because it's an object hash, order is not guaranteed. Order can only be guaranteed in arrays, it's just the way javascript is.

Does that make sense?

**Comment by jfbibeau** [comment]
Yep, makes sense, thanks. I'll have to find another way to do what I need I guess.

**Comment by ksmithut** [comment]
What is it that you're looking to do?

**Comment by jfbibeau** [comment]
I have a project with multiple third party dependencies.
I would like to take each dependency, and minimize it to one JS file.
Then I would like to take each minimized file, and inject it in the html page.

I had it working by iterating over each dep from the hash, minimize every file in the dep, and injecting it, but the order wasn't preserved (as per your explanation, makes sense).

Best I can think of is one of 2 things:
1- Grab ALL dependencies, concat them (which should preserve order), then inject 1 file.
2- Minimize each dep, and inject each minimized file.

**Comment by ksmithut** [comment]
hmm... ya I guess this package doesn't do that out of the box. I'm going to reopen this and see what I can think of, on how to preserve the order. I'll mull over what the data structure might look like. Here's an initial shot at it, but it's pretty different than what the data structure is like now:

```
[
  {
    name: 'jquery',
    files: ['dist/jquery.js']
  },
  {
    name: 'bootstrap',
    files: ['dist/js/bootstrap.js']
  }
]
```

**Comment by jfbibeau** [comment]
No worries, I understand not every package can do everything for everyone. This one is already much better than the others I've used. That data structure would definitely work. Thanks!

**Comment by ksmithut** [comment]
@jfbibeau I finally got around to refactoring it a bit, and have built in this functionality into the latest version (3.9.0). I'm still updating the docs, but you can access the dependencies like this in order using `lib.depsArray`. Let me know what you think :) Apologies for taking so long

**Comment by jfbibeau** [comment]
Thanks! I'll give it a shot.

**Comment by jfbibeau** [comment]
It works! :D Thanks!

**Comment by ksmithut** [comment]
Awesome :)
