### ISSUE TITLE
match files by package name

### ISSUE THREAD

**Issue by lazabogdan** [ksmithut/bower-files#59]
I'm looking for a way to get the results from match in the .deps format:

```javascript
lib.match('**/*.js').deps;
/*
{
    bootstrap: ['...']
}
*/
```

instead of
```javascript
lib.match('**/*.js').files;
/*
[ 'bootstrap/...', '...' ]
*/
```

Adding the package name in the glob doesn't seem to work either.

```javascript
lib.match('bootstrap/**/*.js').files;
```

So I can get the match results for specific packages.
Is there any way to achieve this using the existing API?

**Comment by lazabogdan** [comment]
Actually, I was thinking too much. 

I can get the results for a specific package with a simple filter:

```javascript
files.match('**/*.js').files.filter(function(file) {
    return file.indexOf( path.join('bower_components', 'bootstrap') + path.sep ) !== -1;
});
```

**Comment by ksmithut** [comment]
@lazabogdan To make things a little cleaner you could use:

```js
lib.match('**/bootstrap/**/*.js').files
```

the reason you need the leading `**` is because it's matching on the absolute file path from the root of your file system. Let me know if that works for you.

**Comment by lazabogdan** [comment]
@ksmithut Right! I tried that but with a single `*`. I thought it was matching on relative paths to `process.cwd`. Thanks.

**Comment by ksmithut** [comment]
You bet. I think that's good behavior to match based on process.cwd. I'll leave this open for that reason. I'll get around to it sometime this weekend

**Comment by lazabogdan** [comment]
Cool ;)

**Comment by ksmithut** [comment]
@lazabogdan The latest version (3.9.0) has been published and now matches off of the relative path. Let me know how that works for you.
