### ISSUE TITLE
"No main" handling

### ISSUE THREAD

**Issue by daghoidahl** [ksmithut/bower-files#60]
Hi,

Looking for a of sorting bower components by dependency order for minification, I found your package which seems to solve my problem. Thanks!

In my own project, I ran into one problem with Modernizr, which seems to be missing the "main" property, and hence bower-files bailed out. In an experiment, I removed the assertion in component.js that tests for the existence of this property. This solved the problem, and everything still seems to be working fine. There's one unit test that ensure that this assertion is in place, but all the other unit tests also run fine without this assertion.

From the test file, it looks like some code to support the 2.x version. Could you tell me why this tool needs to quit if the "main" property is missing?

**Comment by ksmithut** [comment]
At one point I had put in a warning stating that the `main` property hadn't been defined by the package, but could be overridden. I think that in the refactor, I had forgotten about the message and just let it throw. I felt that at least a descriptive warning would prevent someone from scratching their heads as to why the files from a component weren't included.

What would you think about a warning log in the console? or maybe just enable logging it with a debug environment flag? I do agree that just failing is kind of a hinderance.

**Comment by daghoidahl** [comment]
A warning log sounds good to me.

I'm not very familiar with bower and the consequences of missing the `main` property, as I just swooped in to fix a problem my team has with bower components being concatenated and minified in the wrong order. All I know about it is that _angular-bootstrap-slider_, which is the package that has a dependency to _modernizr_ (with the missing `main`) seems to be working fine for us.

**Comment by ksmithut** [comment]
@daghoidahl I pushed up your changes to 3.10.0. Let me know if it works for you :)

**Comment by daghoidahl** [comment]
This works. Thanks for the quick response! It feels a lot better to include a supported version of a library than a private fork.
