### ISSUE TITLE
Fails with bower install --production

### ISSUE THREAD

**Issue by ollisal** [ksmithut/bower-files#62]
Bower has the --production flag which causes it to skip installing devDependencies. Even if this is used, https://github.com/ksmithut/bower-files/blob/master/lib/component.js#L31 ends up trying to read `.bower.json` files from all the devDependencies, and thus the call to BowerFiles throws.

There seems to be no option to make BowerFiles handle this case. The `dev` option (defaulting to false anyway) just skips the devDependencies from the output, but their .bower.json files are read anyway.

**Comment by ksmithut** [comment]
That's a good point, I don't think I accounted for that. I'll work that in this week.

**Comment by ksmithut** [comment]
Alright, I've published a new version to npm. Give it a shot :)

**Comment by ksmithut** [comment]
@ollisal Let me know if this is working for you

**Comment by ollisal** [comment]
Ah sorry,

not anticipating such a quick response, I initially worked around this issue by adding fake empty-ish .bower.json files to my repo, for bower-files to use when bower install --production had been ran.

Seems to work fine with 3.11.1, even with this hack removed, thanks. :+1:
