### ISSUE TITLE
ReferenceError on Require.

### ISSUE THREAD

**Issue by paroxp** [ksmithut/bower-files#64]
Hey!

I'm getting the following error, when I attempt to require the bower-files module.

```
var lib = require('bower-files')();
```

The above line, triggers the error below.

```
[17:25:14] ReferenceError: arguments is not defined in task 'bower' at node_modules\mout\
lang\isArguments.js:5:25
[17:25:14] 'bower' errored after 2.88 ms
[17:25:14] ReferenceError: arguments is not defined
    at node_modules\mout\lang\isArguments.js:5:25
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at Object.exports.runInNewContext (vm.js:49:17)
    at Module._compile (node_modules\gulp-loader\Module.coffee:88:17)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at Module.load (node_modules\gulp-loader\Module.coffee:64:43)
    at Module.require (utopia\node_modules\gulp-loader\Module.coffee:53:16)
    at require (node_modules\gulp-loader\Module.coffee:72:21)
    at node_modules\mout\lang.js:13:21
```

**Comment by ksmithut** [comment]
I'll take a look, seems odd though... What version of node and npm are you running?

**Comment by paroxp** [comment]
npm 3.3.8
node 4.1.2

**Comment by paroxp** [comment]
I should also mention, it appears on Windows 10.

**Comment by paroxp** [comment]
Actually, the same issue appears on OSX, NPM 2.14.0 Node 0.12.4

**Comment by ksmithut** [comment]
@paroxp Are you using bower-files in a gulp workflow? What bower-dependencies do you have?

**Comment by paroxp** [comment]
Yes I am.

```
{
  "devDependencies": {
    "bower-files": "^3.11.1",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-loader": "^1.1.2",
    "gulp-sass": "^2.0.4",
    "gulp-uglify": "^1.4.2"
  }
}
```

**Comment by ksmithut** [comment]
What does your `bower` task look like?

**Comment by paroxp** [comment]
```
var concat = require('gulp-concat');
var lib = require('bower-files')();

module.exports = function() {
  gulp
    .src(lib.ext('js').files)
    .pipe(concat('plugins.min.js'))
    .pipe(gulp.dest('./src/js'));

  gulp
    .src(lib.ext(['css', 'sass', 'scss', 'less']).files)
    .pipe(concat('_plugins.scss'))
    .pipe(gulp.dest('./src/sass'));

  gulp
    .task(['sass', 'uglify']);
};
```

Mind, it's loaded with the 'gulp-loader' package from the gulp directory. Although, none of the other tasks seem to be bothered.

**Comment by ksmithut** [comment]
I'm having trouble replicating it with my set of tests, but from the stack trace, it looks like gulp-loader is doing something odd with running modules in different contexts. That in combination with the odd way that the `mout` module was developed causes some issues... I might need more time to figure out which module is causing the issue.

**Comment by paroxp** [comment]
No worries :)

Here's my repo, if you'd like to replicate an issue:

https://github.com/paroxp/utopia

May be helpful.

**Comment by ksmithut** [comment]
That helps a lot. Here is what I've discovered so far:

1. In your project `bower.json`, you have an empty string in your `"main"` property. This isn't causing your issue, but it will cause some problems.
2. I tried building a bower task without gulp-loader, and the task ran fine. It appears gulp-loader is doing some odd 'contextifying' when it's trying to run it's module loader, which is causing issues with the `mout` module.

Options right now:
* `mout` is a dependency of `bower-config`, which is used directly by `bower` and `bower-files`. It's used to load `.bowerrc` configuration and such. I could use a different module to find it, but it will make `bower-files` less compatible with `bower` config files in the future as `bower` evolves.
* You could try a different gulp task loader to see if that works for you. In addition to that, you'll want to fix your `main` property in your `bower.json`. I'm going to push a check for that error.

**Comment by ksmithut** [comment]
version `3.11.2` has been published to account for an empty string in the "main" property in the `bower.json`

**Comment by paroxp** [comment]
Great, thanks for that! I'll give it a shot tonight :)

Sorry to cause bother :(

**Comment by ksmithut** [comment]
It's not your fault :) It's a miracle that any of this software written by hundreds of developers work together anyway. Let me know what you find :)

**Comment by paroxp** [comment]
Still nothing I'm afraid.

I'll try different task loader perhaps. 
Don't really fancy exchanging bower module, as your's is simple and nice :)

**Comment by ksmithut** [comment]
Ah, what I was saying that I would have to change my dependency, which is `bower-config`. I use `bower-config` internally, so you wouldn't have to change which version of bower you're using, I would just have to figure out a way of doing what they're doing, but without `bower-config` and `mout`.

**Comment by ksmithut** [comment]
@paroxp It's been a while. I've neglected this module for a long time and it seems that bower has moved on with its standards. I'm going to rewrite this module to make it much more maintainable and standards compliant, but if you're still looking for something to use, [wiredep](https://www.npmjs.com/package/wiredep) is a good alternative.

**Comment by ksmithut** [comment]
@paroxp Feel free to reopen if you're still having issues.
