### ISSUE TITLE
Using path as a package is not working

### ISSUE THREAD

**Issue by nebulousGirl** [ksmithut/bower-files#66]
With bower you can specify a path instead of a name for a package and give a name to the package.

For example, I have this folder structure:
```
- project-1
---- bower_components
------ dep-1
---- bower.json with dependency "../shared/dep-1"
- project-2
- shared
---- dep-1
------ bower.json with name "dep-1"
```
bower-files is trying to locate the dependency using "../shared/dep-1" from bower_components instead of the name "dep-1", obviously it fails.

Is there a way around this?

**Comment by ksmithut** [comment]
hmmm... Currently there is not, but that would be an important feature to add, especially because it's supported by bower. I'll take a look at this right now and see if it's an easy thing to add.

**Comment by ksmithut** [comment]
@nebulousGirl What does your bower.json look like? Or at least an example of what it looks like?

**Comment by nebulousGirl** [comment]
dep-1/bower.json:
```
{
  "name": "base-theme",
  "dependencies": {
    "backbone": "~1.1.2",
    "jquery": "~1.10",
    "normalize.css": "~3.0.2"
  },
  "main": [
      "./dist/assets/css/main.min.css",
      "./dist/assets/js/main.min.js"
  ]
}
```
project-1/bower.json:
```
{
  "name": "main-theme",
  "dependencies": {
    "./../shared/dep-1": "*"
  }
}
```
It could also be something that is manually passed as an option, like aliases

**Comment by ksmithut** [comment]
So out of the box, you could symlink your `shared/dep1/` package into your `bower_components/` directory, but I'm going to try and support the default behavior. I'm having trouble finding bower's documentation on this feature. Do you have a link to the page with that feature documented?

**Comment by ksmithut** [comment]
Alright, I think I found the link: https://github.com/bower/spec/blob/master/json.md#dependencies

But this is what it says:

> Local paths may be used as values for local development, but they will be disallowed when registering.

So it says that the values should be the local paths. Based on that description, your `bower.json` should like like this:

```json
{
  "name": "main-theme",
  "dependencies": {
    "dep-1": "./../shared/dep-1"
  }
}
```

I tried running `bower install ../local-path --save` and that's the kind of setup that it did. But when it did that, it copied the files to my `bower_components` directory. Could you confirm this behavior?

**Comment by nebulousGirl** [comment]
I just left work. I will try that tomorrow.

I had a hard time trying to figure out the format to put in the bower file. The documentation is missing some examples. I hadn't thought that I could use a relative path directly with bower install.

Thanks for your time!

**Comment by ksmithut** [comment]
You bet :) Let me know what you're able to get to work. I'll be available tomorrow in the afternoon (probably going to sleep in after watching Star Wars really late).

**Comment by nebulousGirl** [comment]
I tried using the path as a value like in your example and it works. 

Thanks again!
