### ISSUE TITLE
DevDependencies that depend on normal dependencies are incorrectly ordered

### ISSUE THREAD

**Issue by stickywes** [ksmithut/bower-files#68]
> Right now they come before the normal dependencies, but I may be convinced to change that if someone runs into issues.

I guess I'm the first someone after all this time, go me!

While developing a current project, I am including a jQuery plugin called "mockjax" in order to generate mock API responses. I have defined that jQuery plugin is one of my "devDependencies".  However, since jQuery is both a dev dependency and a non-dev dependency, it's only defined in my "dependencies" within bower.json.

This means that when I am creating my "libs.js" during development my jQuery plugin is being defined before jQuery, which generates an error because no jQuery object exists yet.

The workaround is really easy, which is to define jQuery as both a "dependency" and a "devDependency" but my understanding was that this should be unnecessary.  This also worked fine in the 2.x version.

**Comment by ksmithut** [comment]
That's a good point. I'll work this in. Because it might be a breaking change, would you be alright if I made it an option that you pass into `.dev()` method? something like `.dev('after')` or `{ dev: 'after' }`?

**Comment by stickywes** [comment]
Seems like a good idea.  The existing ordering approach has been around long enough that there's probably a fair amount of people who depend on it now.

**Comment by ksmithut** [comment]
Alright, I've published version 3.13.1 with the proposed changes. I've got tests verifying that it works, but let me know if you run into any issues :)

**Comment by stickywes** [comment]
Looks like it does the trick, thanks!
