### ISSUE TITLE
.ext supporting regex

### ISSUE THREAD

**Issue by darlanmendonca** [ksmithut/bower-files#73]
what you think about use the method .ext with regex, instead only strings? e.g.

```js
bowerFiles().ext('js').files // => return files with extension .js
```

```js
bowerFiles().ext(/eot|svg|ttf|woff|woff2/).files // return files with extension .eot, or .svg, .ttf, .woff, ...
```

**Comment by ksmithut** [comment]
That would be interesting. This can kind of already be accomplished using the [.join() method](https://github.com/ksmithut/bower-files#libjoinfont-eot-woff-ttf-svg), or the other option would be to use .match():

```js
bowerFiles().match(/\.(eot|svg|ttf|woff|woff2)$/).files
```

Not as pretty of a regex, but usable. I suppose the `.ext()` with the regex could be a shortcut for those other implementations. Thoughts?

**Comment by hvs-pbierans** [comment]
I have a set of file-extensions in an array called GruntSettings which I already use in various grunt tasks. I'd like to use them for bowerFiles.ext, too. So my thought would be:
```bowerFiles().ext(["eot", "svg", "ttf", "woff", "woff2"]).files```
ext = function (what){ switch (typeof what) ...) --- ;)

**Comment by ksmithut** [comment]
@hvs-pbierans You can accomplish this using an array in the following way:

```js
bowerFiles().join({ fonts: [ "eot", "svg", "ttf", "woff", "woff2" ] }).files.fonts
```
